const ADD_INGREDIENT = 'ADD_INGREDIENT';
const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
const LOAD_INITIAL_IINGREDIENTS = 'LOAD_INITIAL_IINGREDIENTS';
const ERROR_LOADING_INITIAL_IINGREDIENTS = 'ERROR_LOADING_INITIAL_IINGREDIENTS';

const PURCHASE_ORDER = 'PURCHASE_ORDER';
const CANCEL_ORDER = 'CANCEL_ORDER';
const LIST_ORDERS = 'LIST_ORDERS';
const ERROR_LOADING_LIST_ORDERS = 'ERROR_LOADING_LIST_ORDERS';

const PLACE_ORDER = 'PLACE_ORDER';
const ERROR_PLACING_ORDER = 'ERROR_PLACING_ORDER';
const INITIATE_ORDER_PURCHASE = 'INITIATE_ORDER_PURCHASE';
const END_ORDER_PURCHASE = 'END_ORDER_PURCHASE';
const INITIATE_FETCH_ORDERS = 'INITIATE_FETCH_ORDERS';

export {
  ADD_INGREDIENT,
  REMOVE_INGREDIENT,
  LOAD_INITIAL_IINGREDIENTS,
  PURCHASE_ORDER,
  CANCEL_ORDER,
  LIST_ORDERS,
  PLACE_ORDER,
  ERROR_LOADING_INITIAL_IINGREDIENTS,
  ERROR_LOADING_LIST_ORDERS,
  ERROR_PLACING_ORDER,
  INITIATE_ORDER_PURCHASE,
  END_ORDER_PURCHASE,
  INITIATE_FETCH_ORDERS
};
